travis:
  secure:
    BINSTAR_TOKEN: am2wTb3Y6AfSkOkAiDJQbxSAmhwXEMeQlhL9h/11q9TIZ1qBssGfHPiCXE0XjoRqJof8ks3SxtGbGxuXRbDqJR79+/zJZoZZLZC9A5wkkbL6Yji+s6xoKkE8JzIeLopbR+309I3rLwGDej4khMz/q2i1YtdINcRwmYVdxcFRkOCtKxcZLqtGvARC1REXk4+kuONDzGWGaptdsxrrZT8vmJetlf+dhrFGYiw76dz+yoPtZ+eYKWLiXKs9F8R+6mfo79hXWOroVlmv4S700rp904t977qcPideij4ZPL/wLEI4g1t1zOhEf9DqPUAAeYKFWUyILJRjGf4O+CaQqv2w23cxOE4W4ZIHBPuh6pjVnJGJUoLxl8ZQP5WWb0GXGp3e9932yMCccwrMJ1fYxLyKKPP53NJmG7pVAkHEhUyByp3Ynsu6bOfDLNpMtEjdCr0Ljx5eXK8TVPZnVdUjQYKDm92c9jJkqEjJA310rp718O7gYNlPuT1150/Tc/NCtXfc+W/3f+pJ1yVJBIo74/9vUPN2zNHhfi7GSTc5OZWiLZJBM76X5so/XavqafZXDUVoBYhr+c7uW+IWZSRsABwIcV/L5uTzgjqeCzHEo84dH95Upd7eSBcI+uxcrpnGxb3s9kaC+t50YVIaFEG9hBml/twujrS+o9rXril/sbdjgLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
